tls_server_config:
  # Certificate and key files for server to use to authenticate to client.
  cert_file: /etc/prometheus/cert.crt
  key_file: /etc/prometheus/server.key

basic_auth_users:
  alice: $2a$12$0rAWnyIL6ZCKpwUs6vAT2uy89Hmy.ZmARWrWzh88roldltUs2pN5q
