global:
  scrape_interval: 15s

storage:
  tsdb:
    retention:
      time: 30m

scrape_configs:
  - job_name: node-exporters
    scrape_interval: 5s
    static_configs:
      - targets:
          - 51.159.232.57:9100
          - 51.159.237.20:9100
        labels:
          provider: scaleway
          type: vm
          # dont do this
          #instance: whatever
          #
  - job_name: apache-exporters
    scrape_interval: 10s
    static_configs:
      - targets:
          - 51.159.232.57:9117
          - 51.159.237.20:9117
        labels:
          app_name: my-super-app

  - job_name: my-apps
    fallback_scrape_protocol: PrometheusText0.0.4
    scrape_interval: 5s
    static_configs:
      - targets:
         - 172.16.2.45:8282
         - 172.16.2.45:8383
        labels:
          group: lab
          app_name: static_metrics

