global:
  scrape_interval: 15s

storage:
  tsdb:
    retention:
      time: 30m

scrape_configs:
  - job_name: node-exporters
    scrape_interval: 5s
    static_configs:
      - targets:
          - 51.159.232.57:9100
          - 51.159.237.20:9100
        labels:
          provider: scaleway
          type: vm

